In [38]:
import numpy as np

In [39]:
arr1=np.arange(9).reshape(3,3)  #elemental

In [40]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
arr2=np.arange(36,45).reshape(3,3)
arr2

array([[36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [42]:
arr1+arr2

array([[36, 38, 40],
       [42, 44, 46],
       [48, 50, 52]])

In [43]:
arr1-arr2

array([[-36, -36, -36],
       [-36, -36, -36],
       [-36, -36, -36]])

In [44]:
arr1*arr2

array([[  0,  37,  76],
       [117, 160, 205],
       [252, 301, 352]])

In [45]:
arr1/arr2

array([[0.        , 0.02702703, 0.05263158],
       [0.07692308, 0.1       , 0.12195122],
       [0.14285714, 0.1627907 , 0.18181818]])

In [47]:
arr1//arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [48]:
arr1**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [49]:
arr1%arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
np.add(arr1,arr2)

array([[36, 38, 40],
       [42, 44, 46],
       [48, 50, 52]])

In [51]:
np.subtract(arr1,arr2)

array([[-36, -36, -36],
       [-36, -36, -36],
       [-36, -36, -36]])

In [52]:
np.power(arr1,4)

array([[   0,    1,   16],
       [  81,  256,  625],
       [1296, 2401, 4096]])

In [61]:
#matrix multiplication
arr3=np.dot(arr1,arr2)

In [54]:
arr1*arr2

array([[  0,  37,  76],
       [117, 160, 205],
       [252, 301, 352]])

In [55]:
arr1.shape

(3, 3)

In [56]:
arr2.shape

(3, 3)

In [57]:
arr1.sum()

36

In [58]:
arr1.mean()

4.0

In [59]:
arr1.std()

2.581988897471611

In [60]:
arr1.ptp()  #highest-lowest

8

In [63]:
arr3.ptp()
arr3

array([[123, 126, 129],
       [474, 486, 498],
       [825, 846, 867]])

In [64]:
arr3.max()-arr3.min()

744