In [1]:
import numpy as np

In [2]:
#2 d arrays
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr2=np.arange(9).reshape((3,3))

In [5]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
arr2.ndim

2

In [9]:
arr2.shape

(3, 3)

In [10]:
arr2.size

9

In [11]:
arr2.itemsize

8

In [12]:
arr2.max()

8

In [13]:
arr2.min()

0

In [14]:
arr2.sum()

36

In [15]:
arr2.mean()

4.0

In [16]:
arr2.std()

2.581988897471611

In [17]:
np.full((3,4),-1)

array([[-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [19]:
#3d arrays
arr3=np.array([[[1,2,3],[4,5,6]],[[3,4,5],[5,6,7]]])

In [20]:
arr3.ndim

3

In [22]:
arr4=np.arange(12).reshape(2,3,2)

In [23]:
arr4.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
#4d array
arr5=np.arange(72)


In [27]:
arr5=arr5.reshape((4,3,2,3))

In [28]:
arr5.ndim

4