##indexing arrays

In [1]:
import numpy as np

In [2]:
arr1=np.arange(15,42)

In [6]:
len(arr1)
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41])

In [5]:
arr1[5]

20

In [7]:
arr1[-1]

41

In [8]:
arr1[26]

41

In [9]:
arr1[4]=674868

In [10]:
arr1   #mutable entities

array([    15,     16,     17,     18, 674868,     20,     21,     22,
           23,     24,     25,     26,     27,     28,     29,     30,
           31,     32,     33,     34,     35,     36,     37,     38,
           39,     40,     41])

In [12]:
arr2=arr1.reshape(3,9)

In [15]:
arr2.ndim
arr2

array([[    15,     16,     17,     18, 674868,     20,     21,     22,
            23],
       [    24,     25,     26,     27,     28,     29,     30,     31,
            32],
       [    33,     34,     35,     36,     37,     38,     39,     40,
            41]])

In [16]:
arr2[0][1]

16

In [18]:
arr2[-1,-1]

41

In [19]:
#first row
arr2[0,]

array([    15,     16,     17,     18, 674868,     20,     21,     22,
           23])

In [20]:
arr2[1,]   #second rows

array([24, 25, 26, 27, 28, 29, 30, 31, 32])

In [21]:
arr2[,0]

SyntaxError: ignored

In [22]:
arr1

array([    15,     16,     17,     18, 674868,     20,     21,     22,
           23,     24,     25,     26,     27,     28,     29,     30,
           31,     32,     33,     34,     35,     36,     37,     38,
           39,     40,     41])

In [30]:
arr1[4:29:3]

array([674868,     22,     25,     28,     31,     34,     37,     40])

In [31]:
arr1[::-1]

array([    41,     40,     39,     38,     37,     36,     35,     34,
           33,     32,     31,     30,     29,     28,     27,     26,
           25,     24,     23,     22,     21,     20, 674868,     18,
           17,     16,     15])

In [32]:
arr1[-1:-28:-1]   #reverse

array([    41,     40,     39,     38,     37,     36,     35,     34,
           33,     32,     31,     30,     29,     28,     27,     26,
           25,     24,     23,     22,     21,     20, 674868,     18,
           17,     16,     15])

In [33]:
#2d arrays

In [34]:
arr2

array([[    15,     16,     17,     18, 674868,     20,     21,     22,
            23],
       [    24,     25,     26,     27,     28,     29,     30,     31,
            32],
       [    33,     34,     35,     36,     37,     38,     39,     40,
            41]])

In [35]:
arr2[1:,]

array([[24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41]])

In [36]:
arr2[1:,6:]

array([[30, 31, 32],
       [39, 40, 41]])

In [37]:
arr2[0:3,5:8]

array([[20, 21, 22],
       [29, 30, 31],
       [38, 39, 40]])

In [38]:
#fancy indexing
indices=[[3,4],[2,4]]
indices=np.array(indices)

In [39]:
indices

array([[3, 4],
       [2, 4]])

In [40]:
arr1[indices]

array([[    18, 674868],
       [    17, 674868]])