In [1]:
import numpy as np

In [7]:
array1=np.linspace(1,10,9)

In [9]:
array1=array1.reshape(3,3)

In [11]:
array1

array([[ 1.   ,  2.125,  3.25 ],
       [ 4.375,  5.5  ,  6.625],
       [ 7.75 ,  8.875, 10.   ]])

In [20]:
array2=np.linspace(3,4,9)

In [21]:
array2=array2.reshape(3,3)

In [22]:
array2

array([[3.   , 3.125, 3.25 ],
       [3.375, 3.5  , 3.625],
       [3.75 , 3.875, 4.   ]])

In [25]:
#concatenation
np.concatenate([array1,array2],axis=0)

array([[ 1.   ,  2.125,  3.25 ],
       [ 4.375,  5.5  ,  6.625],
       [ 7.75 ,  8.875, 10.   ],
       [ 3.   ,  3.125,  3.25 ],
       [ 3.375,  3.5  ,  3.625],
       [ 3.75 ,  3.875,  4.   ]])

In [24]:
np.concatenate([array1,array2],axis=1)

array([[ 1.   ,  2.125,  3.25 ,  3.   ,  3.125,  3.25 ],
       [ 4.375,  5.5  ,  6.625,  3.375,  3.5  ,  3.625],
       [ 7.75 ,  8.875, 10.   ,  3.75 ,  3.875,  4.   ]])

In [26]:
#stacking
data1=np.array([3,3,3,4,2,3])
data2=np.array([3,4,5,3,56,7])

In [27]:
data1

array([3, 3, 3, 4, 2, 3])

In [28]:
data2

array([ 3,  4,  5,  3, 56,  7])

In [29]:
np.stack((data1,data2))

array([[ 3,  3,  3,  4,  2,  3],
       [ 3,  4,  5,  3, 56,  7]])

In [30]:
np.stack((array1,array2))

array([[[ 1.   ,  2.125,  3.25 ],
        [ 4.375,  5.5  ,  6.625],
        [ 7.75 ,  8.875, 10.   ]],

       [[ 3.   ,  3.125,  3.25 ],
        [ 3.375,  3.5  ,  3.625],
        [ 3.75 ,  3.875,  4.   ]]])

In [31]:
np.column_stack((data1,data2))

array([[ 3,  3],
       [ 3,  4],
       [ 3,  5],
       [ 4,  3],
       [ 2, 56],
       [ 3,  7]])

In [32]:
np.hstack((data1,data2))

array([ 3,  3,  3,  4,  2,  3,  3,  4,  5,  3, 56,  7])

In [35]:
np.vstack((data1,data2))

array([[ 3,  3,  3,  4,  2,  3],
       [ 3,  4,  5,  3, 56,  7]])

In [38]:
np.split(array1,5)

ValueError: ignored

In [41]:
np.split(array1,3)

[array([[1.   , 2.125, 3.25 ]]),
 array([[4.375, 5.5  , 6.625]]),
 array([[ 7.75 ,  8.875, 10.   ]])]

In [40]:
array1.shape

(3, 3)

In [42]:
stacked=np.arange(16).reshape(4,4)

In [43]:
stacked

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
np.hsplit(stacked,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]), array([[ 1],
        [ 5],
        [ 9],
        [13]]), array([[ 2],
        [ 6],
        [10],
        [14]]), array([[ 3],
        [ 7],
        [11],
        [15]])]

In [47]:
np.vsplit(stacked,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]