In [16]:
import numpy as np

In [17]:
info=np.array([3,4,5,6,3,4,66,7])

In [18]:
info

array([ 3,  4,  5,  6,  3,  4, 66,  7])

In [21]:
np.save('data_array.npy',info)  #binary format

In [22]:
np.load('data_array.npy')

array([ 3,  4,  5,  6,  3,  4, 66,  7])

In [23]:
#savetxt
data=np.arange(100).reshape(25,4)

In [24]:
np.savetxt('data__textfile.txt',data)

In [25]:
np.genfromtxt('data__textfile.txt')

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.],
       [24., 25., 26., 27.],
       [28., 29., 30., 31.],
       [32., 33., 34., 35.],
       [36., 37., 38., 39.],
       [40., 41., 42., 43.],
       [44., 45., 46., 47.],
       [48., 49., 50., 51.],
       [52., 53., 54., 55.],
       [56., 57., 58., 59.],
       [60., 61., 62., 63.],
       [64., 65., 66., 67.],
       [68., 69., 70., 71.],
       [72., 73., 74., 75.],
       [76., 77., 78., 79.],
       [80., 81., 82., 83.],
       [84., 85., 86., 87.],
       [88., 89., 90., 91.],
       [92., 93., 94., 95.],
       [96., 97., 98., 99.]])