In [2]:
import numpy as np

In [3]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [5]:
#arrays
arr=np.array([3,4,5,3,45,3,4,5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
np.array((3,4,5,3,45,3,4,5))

array([ 3,  4,  5,  3, 45,  3,  4,  5])

In [8]:
np.array({43,5,3,5,6})

array({43, 3, 5, 6}, dtype=object)

In [11]:
np.array([4,5,6,3,5,'hfhjfhd'])

array(['4', '5', '6', '3', '5', 'hfhjfhd'], dtype='<U21')

In [14]:
arr1=np.arange(10,50,5)

In [15]:
arr1

array([10, 15, 20, 25, 30, 35, 40, 45])

In [16]:
arr1.shape

(8,)

In [17]:
arr1.size

8

In [18]:
arr1.ndim

1

In [19]:
arr.itemsize

8

In [20]:
len(arr)

8

In [21]:
arr1.dtype

dtype('int64')

In [24]:
np.linspace(2,10,15)

array([ 2.        ,  2.57142857,  3.14285714,  3.71428571,  4.28571429,
        4.85714286,  5.42857143,  6.        ,  6.57142857,  7.14285714,
        7.71428571,  8.28571429,  8.85714286,  9.42857143, 10.        ])

In [26]:
np.full(8,76)

array([76, 76, 76, 76, 76, 76, 76, 76])